variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - $env:UNITY="C:\UnityEditors\2022.1.3f1c1\Editor\Unity.exe"
  - $env:APP_NAME=before-dawn
  - $env:APP_BUNDLE_ID=com.VRcollab.BeforeDawn
  - $env:APP_VERSION=1.0.0
  - $env:APP_TARGET=WebGL
  - ossutil config -e ${env:ALIYUN_ENDPOINT} -i ${env:ALIYUN_ACCESS_KEY_ID} -k ${env:ALIYUN_ACCESS_KEY_SECRET}
  # CI Bucket
  - $env:OSS_DIR_BASE="oss://${env:ALIYUN_CI_ARTIFACTS_BUCKET}/${env:APP_BUNDLE_ID}/${env:CI_COMMIT_SHA}"
  - $env:OSS_URL_BASE="https://${env:ALIYUN_CI_ARTIFACTS_BUCKET}.oss-cn-hangzhou.aliyuncs.com/${env:APP_BUNDLE_ID}/${env:CI_COMMIT_SHA}"
  - $env:OSS_URL_BASE_SG="https://${env:ALIYUN_CI_ARTIFACTS_BUCKET_SG}.oss-ap-southeast-1.aliyuncs.com/${env:APP_BUNDLE_ID}/${env:CI_COMMIT_SHA}"
  # Webapp Bucket (for webapp preview)
  - $env:OSS_WEBAPP_BASE="oss://${env:ALIYUN_CI_WEBAPP_BUCKET}/${env:APP_BUNDLE_ID}/${env:CI_COMMIT_SHA}"
  - $env:OSS_WEBAPP_LATEST="oss://${env:ALIYUN_CI_WEBAPP_BUCKET}/${env:APP_BUNDLE_ID}/latest"
  - $env:OSS_WEBAPP_URL_BASE="https://ci-webapp.vrcollab.com.cn/${env:APP_BUNDLE_ID}/${env:CI_COMMIT_SHA}"
  - $env:OSS_WEBAPP_URL_LATEST="https://ci-webapp.vrcollab.com.cn/${env:APP_BUNDLE_ID}/latest"
  # Release Bucket
  - $env:OSS_RELEASE_BASE="oss://${env:ALIYUN_RELEASES_BUCKET}/${env:APP_BUNDLE_ID}"

build:
  stage: build
  tags:
    - ci-windows
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - Library/
  script:
    - ./build.ps1

deploy:
  stage: deploy
  tags:
    - ci-windows
  when: manual
  only:
    - master
  script:
    # Copy artifacts
    - ossutil cp ${env:OSS_DIR_BASE}/${env:APP_BUNDLE_ID}.zip ${env:OSS_RELEASE_BASE}/${env:APP_VERSION}.zip
    - ossutil cp ${env:OSS_DIR_BASE}/package.json ${env:OSS_RELEASE_BASE}/${env:APP_VERSION}.json
    # Make artifacts as the latest release
    - ossutil create-symlink ${env:OSS_RELEASE_BASE}/latest.zip ${env:OSS_RELEASE_BASE}/${env:APP_VERSION}.zip
    - ossutil create-symlink ${env:OSS_RELEASE_BASE}/latest.json ${env:OSS_RELEASE_BASE}/${env:APP_VERSION}.json
